version: "3.8"

services:
  app:
    build: .
    ports:
      - 8000:8000
      - 6080:6080
      - 8889:8889
    environment:
      - DISPLAY=:99
      - ACCOUNT_MANAGER_DATABASE_URL=sqlite:////app/data/account_manager.db
    volumes:
      - ../files/data:/app/data
    restart: unless-stopped
    networks:
      - dokploy-network
      - default

networks:
  dokploy-network:
    external: true
